"""Focused real-Skill regression for pure column-structure convergence.

The fixtures are generated by Excel COM in the UX acceptance task.  This test
does not save or launch Excel: it exercises the live in-memory App action path,
prints compact value/formula/cache evidence, and requires the final logical
comparison to converge to zero visual row differences.
"""

from __future__ import annotations

from collections import Counter
import copy
import hashlib
import json
import os
import time

import sow_merge_tool as smt
from _gui_self_test_logical_column_actions import _pump, _wait_for_view


ROOT = r"C:\Users\dd\AppData\Local\Temp\sow_ux_5_3_20260723_001"
MINE = os.environ.get(
    "SOW_REAL_SKILL_MINE",
    os.path.join(ROOT, "cases", "Skill", "mine", "Skill.xlsx"),
)
THEIRS = os.environ.get(
    "SOW_REAL_SKILL_THEIRS",
    os.path.join(ROOT, "cases", "Skill", "theirs", "Skill.xlsx"),
)
SHEET = "SkillTimeline@design"


def _sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def _short(value, limit: int = 180):
    text = repr(value)
    return text if len(text) <= limit else text[: limit - 3] + "..."


def _write_markers(app):
    operation_attrs = (
        "manual_a_cell_ops",
        "manual_b_cell_ops",
        "manual_a_formula_cache_ops",
        "manual_b_formula_cache_ops",
        "manual_a_row_ops",
        "manual_b_row_ops",
        "manual_a_column_ops",
        "manual_b_column_ops",
        "manual_sheet_ops",
        "undo_stack",
    )
    return {
        "operations": {
            name: copy.deepcopy(getattr(app, name))
            for name in operation_attrs
        },
        "modified": (
            bool(app.modified_a),
            bool(app.modified_b),
            frozenset(app.modified_sheets_a),
            frozenset(app.modified_sheets_b),
        ),
        "source_hashes": (_sha256(MINE), _sha256(THEIRS)),
    }


def _wrap_timing(owner, name: str, timings: dict[str, list[float]]):
    original = getattr(owner, name)

    def wrapped(*args, **kwargs):
        started = time.perf_counter()
        try:
            return original(*args, **kwargs)
        finally:
            timings.setdefault(name, []).append(
                (time.perf_counter() - started) * 1000.0
            )

    setattr(owner, name, wrapped)


def _profiled_apply(view, source_side: str, target_side: str):
    timings: dict[str, list[float]] = {}
    for name in (
        "_capture_column_formula_transformations",
        "_column_action_workbook_snapshot",
        "_prepare_column_copy_payload",
        "_apply_column_formula_transformations",
        "_shift_worksheet_columns_fast",
        "_apply_column_copy_payload",
        "refresh",
    ):
        _wrap_timing(view, name, timings)
    started = time.perf_counter()
    plan = view._apply_selected_column_block(source_side, target_side)
    total_ms = (time.perf_counter() - started) * 1000.0
    summary = {
        name: {
            "calls": len(values),
            "total_ms": round(sum(values), 3),
            "max_ms": round(max(values), 3),
        }
        for name, values in timings.items()
    }
    snapshot_ms = sum(timings.get("_column_action_workbook_snapshot", ()))
    formula_capture_ms = sum(
        timings.get("_capture_column_formula_transformations", ())
    )
    refresh_ms = sum(timings.get("refresh", ()))
    summary["phase_rollup"] = {
        "total_ms": round(total_ms, 3),
        "snapshot_including_formula_ms": round(snapshot_ms, 3),
        "formula_capture_ms": round(formula_capture_ms, 3),
        "snapshot_excluding_formula_ms": round(
            max(0.0, snapshot_ms - formula_capture_ms), 3
        ),
        "refresh_ms": round(refresh_ms, 3),
        "mutation_and_other_ms": round(
            max(0.0, total_ms - snapshot_ms - refresh_ms), 3
        ),
    }
    return plan, summary


def _diff_diagnostics(view, limit: int = 20):
    cache = view._active_column_comparison_cache()
    raw_frequency = Counter()
    visual_frequency = Counter()
    visual_pairs = []
    for pair_idx in range(len(view.row_pairs)):
        raw_frequency.update(view._all_logical_diff_cols_for_pair(pair_idx))
        visual = set(view._visual_diff_cols_for_pair(pair_idx))
        visual_frequency.update(visual)
        if visual:
            visual_pairs.append((pair_idx, visual))

    ws_a_val = view.app.ws_a_val(SHEET)
    ws_b_val = view.app.ws_b_val(SHEET)
    ws_a_edit = view.app.ws_a_edit(SHEET)
    ws_b_edit = view.app.ws_b_edit(SHEET)
    samples = []
    for pair_idx, visual_cols in visual_pairs[:limit]:
        ra, rb = view.row_pairs[pair_idx]
        cells = []
        for logical_col in sorted(visual_cols):
            if logical_col <= 0 or logical_col > len(cache.model.slots):
                cells.append({"logical": logical_col, "sentinel": True})
                continue
            slot = cache.model.slots[logical_col - 1]
            mine_col = slot.mine_col
            theirs_col = slot.theirs_col

            def _value(ws, row, col):
                if row is None or col is None:
                    return None
                return ws.cell(int(row), int(col)).value

            cells.append({
                "logical": logical_col,
                "mine_col": mine_col,
                "theirs_col": theirs_col,
                "state": slot.state,
                "ambiguous": slot.confidence.ambiguous,
                "mine_cache": _short(_value(ws_a_val, ra, mine_col)),
                "theirs_cache": _short(_value(ws_b_val, rb, theirs_col)),
                "mine_edit": _short(_value(ws_a_edit, ra, mine_col)),
                "theirs_edit": _short(_value(ws_b_edit, rb, theirs_col)),
            })
        samples.append({
            "pair_idx": pair_idx,
            "mine_row": ra,
            "theirs_row": rb,
            "cells": cells,
        })

    structural = set(cache.structural_diff_cols)
    return {
        "row_pairs": len(view.row_pairs),
        "visual_pair_count": len(visual_pairs),
        "raw_logical_col_frequency": dict(sorted(raw_frequency.items())),
        "visual_logical_col_frequency": dict(sorted(visual_frequency.items())),
        "structural_cols": sorted(structural),
        "unresolved_cols": sorted(cache.unresolved_cols),
        "visual_structural_overlap": sorted(structural & set(visual_frequency)),
        "first_20_visual_pairs": samples,
    }


def main():
    assert os.path.isfile(MINE), MINE
    assert os.path.isfile(THEIRS), THEIRS
    source_hashes = {"mine": _sha256(MINE), "theirs": _sha256(THEIRS)}
    app = smt.SowMergeApp(MINE, THEIRS)
    try:
        app.root.withdraw()
        view = _wait_for_view(app, SHEET, timeout=180.0)

        # The real Skill fixture should expose the startup window where the
        # view exists but exact diff/column preparation is still incomplete.
        # Exercise the product mutation entry point itself and prove that the
        # read-only gate rejects it without touching any write surface.
        pre_ready_state = view._derive_lifecycle_state()
        assert pre_ready_state != "READY", (
            "real Skill fixture no longer exercised the pre-READY gate",
            pre_ready_state,
            app._edit_workbooks_ready(),
        )
        before_gate = _write_markers(app)
        try:
            view._apply_selected_column_block("B", "A")
        except RuntimeError as exc:
            assert "暂不可用" in str(exc), (pre_ready_state, str(exc))
        else:
            raise AssertionError(
                f"column mutation was not blocked before READY: {pre_ready_state}"
            )
        assert _write_markers(app) == before_gate, (
            "pre-READY column mutation changed write state",
            pre_ready_state,
        )

        deadline = time.time() + 180.0
        while time.time() < deadline:
            edit_ready = app._edit_workbooks_ready()
            lifecycle_state = view._derive_lifecycle_state()
            if edit_ready and lifecycle_state == "READY":
                break
            _pump(app.root, 0.05)
        edit_ready = app._edit_workbooks_ready()
        lifecycle_state = view._derive_lifecycle_state()
        assert edit_ready and lifecycle_state == "READY", {
            "edit_workbooks_ready": edit_ready,
            "lifecycle_state": lifecycle_state,
            "data_ready": bool(getattr(view, "_data_ready", False)),
            "row_model_exact": bool(getattr(view, "_row_model_exact", False)),
            "cache_formula_aware": bool(
                getattr(view, "_cache_formula_aware", False)
            ),
            "pair_diff_full_exact": bool(
                getattr(view, "_pair_diff_full_exact", False)
            ),
            "column_mapping_current": bool(view._column_mapping_is_current()),
        }

        block = view._select_column_block_by_logical_col(12, "B")
        assert block is not None
        first_plan, first_profile = _profiled_apply(view, "B", "A")
        assert first_plan.action_kind == "insert_copy" and first_plan.count == 2

        view._undo_last_action()
        view._select_column_block_by_logical_col(12, "B")
        reapplied = view._apply_selected_column_block("B", "A")
        assert reapplied.action_kind == "insert_copy" and reapplied.count == 2

        deleted_block = view._select_column_block_by_logical_col(24, "A")
        assert deleted_block is not None
        deleted = view._apply_selected_column_block("B", "A")
        assert deleted.action_kind == "delete" and deleted.count == 2

        # Force one exact full compare rather than trusting the action seed.
        view.refresh(row_only=None, rescan=True)
        diagnostics = _diff_diagnostics(view)
        report = {
            "core_mtime": os.path.getmtime(smt.__file__),
            "first_insert_profile": first_profile,
            "diagnostics": diagnostics,
        }
        print(json.dumps(report, ensure_ascii=False, indent=2), flush=True)

        assert not diagnostics["structural_cols"], diagnostics
        assert not diagnostics["unresolved_cols"], diagnostics
        assert diagnostics["visual_pair_count"] == 0, diagnostics
    finally:
        try:
            app._shutdown_root()
        except Exception:
            pass

    assert _sha256(MINE) == source_hashes["mine"]
    assert _sha256(THEIRS) == source_hashes["theirs"]
    print("GUI_SELF_TEST_REAL_SKILL_COLUMN_FORMULA_CONVERGENCE_OK")


if __name__ == "__main__":
    main()
